### PR TITLE
add path and fix issues

### PR DESCRIPTION
**Pull request by truskovskiyk**

### CODE REVIEW

**Comment by Jakobovski** [comment]
@truskovskiyk Why did you close the request?

**Comment by truskovskiyk** [comment]
@Jakobovski I did it by mistake, wanted to update my fork https://github.com/truskovskiyk/decoupled-multimodal-learning. There is a lot of code duplication, but it works.

**Comment by Jakobovski** [comment]
Ah ok.  What are doing with the repository? Are you doing additional research?

**Comment by truskovskiyk** [comment]
yes, for now, I have fixed all paths and added missing files to run the basic example, but the goal is to run on some other dataset, more difficult than MNIST

**Comment by Jakobovski** [comment]
Neat. I think testing it on a more difficult dataset is a good idea. It will be needed if this were to be published into a paper. 

Another interesting approach would be to optimize the algorithm. I think there are lots of improvements that can be made. 

What inspired you to work on this?
I would love if you would keep me updated on your progress:  Zoharj@gmail.com

**Pull request closed without merging**
